### ISSUE TITLE
Lines appearing on footway/in random locations instead of the street.

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#12] opened 2022-07-21 10:36 UTC
Various – this does not occur as often as the measurement tool issue, but when it occurs it takes several attempts to get the restrictions in the correct position (one location took 30 minutes to draft):

![image](https://user-images.githubusercontent.com/109733089/180193497-4a919a7e-75cd-4e81-93a7-ed323bd216d9.png)
![image](https://user-images.githubusercontent.com/109733089/180193509-4b265123-46d6-4553-a34d-0f83ac80f7e0.png)

Telford Road is a specific location that will require attention (drafted under ref TRO/17/92A on TOMs) as the below line won't snap in place:

![image](https://user-images.githubusercontent.com/109733089/180193623-fc0b7d3c-64f3-4dcd-bbba-f173963aedf3.png)

**Comment by Djedouas** [comment] 2022-10-25 13:04
Have you played with **Direction to road centerline** parameter in the restriction form?

see https://github.com/ProjectCentreLimited/TOMs/issues/32#issuecomment-1284193196

if you have already played with it, and the symbol is still randomly appearing, I need you to write a short workflow for me to reproduce the issue (exact location on the map, restriction, zoom-out and zoom-in screenshots)

**Comment by SeanC75** [comment] 2022-11-24 11:29
Would need further development to improve the accuracy of the line when drawing longer lines. Would be a priority 1.

**Comment by Djedouas** [comment] 2022-11-25 09:20
Closed as duplicate of #36

**Closed as completed by Djedouas** 2022-11-25 09:20 UTC
Labels: enhancement
