### ISSUE TITLE
TOMS not opening 

### ISSUE THREAD

**Issue by suhaibahmad97** [ProjectCentreLimited/TOMs#48] opened 2022-11-02 12:40 UTC
TOMS is not opening.

I have tried logging in and out. I have used different web browsers. 
This issue has been ongoing for a number of hours.

How can this issue be resolved in order to get work completed for my manager? 

What is the cause of this issue?

![image](https://user-images.githubusercontent.com/117165256/199491441-c76eba1f-1eb1-4db8-bb94-e5c664fc87b3.png)

**Comment by suhaibahmad97** [comment] 2022-11-02 12:51
When I try to log in, I receive a message. 
What can be done to resolve the issue ?
![image](https://user-images.githubusercontent.com/117165256/199494228-3a62fc92-b3ee-4f91-b047-c6c255de3dd3.png)

**Comment by benoitdm-oslandia** [comment] 2022-11-02 13:00
From the first image, I can see TOMs is opening (look at the bottom 'Loading layer bay.... 13%') but I may be a bit slow. 

Also if you logging/logout too quickly, it may not have the time to clean the session and to provide a new one inducing the second image.

Can you try to wait 5-10 minutes between your last logout and the next logging?

Regards

**Comment by benoitdm-oslandia** [comment] 2022-11-09 15:50
close as duplicate of #35

**Closed as completed by benoitdm-oslandia** 2022-11-09 15:50 UTC
