### ISSUE TITLE
DY - Unable to create, edit or remove restrictions

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#117] opened 2023-04-13 14:37 UTC
See Issue #112 

I have now been able to create a proposal but I cannot add lines, or remove / edit restrictions of any type. Even if it works at first it reappears as it was before the change I made.

I have attempted closing and reopening the app without signing out but it does not help.

**Comment by Djedouas** [comment] 2023-04-13 14:42
Hi,

It's difficult to help here, as I can't reproduce the problem.

Would you be available on Friday 21st to share your screen?

**Comment by Traffic-Orders** [comment] 2023-04-14 08:31
Yes I can be, is 10:00 good for you?

**Comment by Traffic-Orders** [comment] 2023-04-14 08:39
Yes I can be, is 10:00 any good? Of course something sooner would be preferred.

**Comment by Djedouas** [comment] 2023-04-14 10:13
Hi,

Sorry, I have some agenda issues... I have to change the date and won't be available before Monday 24th, the sooner.

You can email me a Teams invitation at any time this day.

**Comment by Traffic-Orders** [comment] 2023-04-14 10:40
________________________________________________________________________________
Microsoft Teams meeting
Join on your computer, mobile app or room device
Click here to join the meeting<https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZThjZmVlZWQtMTFmYS00MDdmLTlmZDUtMjAyMGIxYmE2MDJj%40thread.v2/0?context=%7b%22Tid%22%3a%22482a4ef9-66e4-4e76-9f24-6da09a713ed4%22%2c%22Oid%22%3a%22e7079730-3899-467a-a025-cdaef8a8435e%22%7d>
Meeting ID: 394 102 234 785
Passcode: KJXVRA
Download Teams<https://www.microsoft.com/en-us/microsoft-teams/download-app> | Join on the web<https://www.microsoft.com/microsoft-teams/join-a-meeting>
Learn More<https://aka.ms/JoinTeamsMeeting> | Meeting ***@***.***&messageId=0&language=en-US>
________________________________________________________________________________


_____________________________________________

**Comment by Djedouas** [comment] 2023-04-14 11:51
I mean a Teams invitation on my email address `jacky dot volpes at oslandia.com`, for Monday 24th.

**Comment by Djedouas** [comment] 2023-05-04 14:29
Hi Darren,

I've been working on this issue, and I've just released a test version in the "STAGING" version of TOMS.

You should have received an email indicating that a new stack has been assigned to your account.

Now, when you log into TOMS, you have the choice between the LIVE and the STAGING version:

![image](https://user-images.githubusercontent.com/34267385/236238357-39aae319-6db2-47dc-b3a7-aa709ea8d291.png)

Pick the STAGING version to test and play, to see if the issue is gone.

Thanks,  
Jacky

**Comment by Traffic-Orders** [comment] 2023-05-05 09:54
Hi Jacky

I tried the staging version this morning but I received the error message below

![image](https://user-images.githubusercontent.com/109733089/236427635-325e4b9b-f569-4b91-bc9e-9d955b064574.png)

and I was unable to progress to the CEC map.

![image](https://user-images.githubusercontent.com/109733089/236427935-9af5d6c6-f116-468a-9692-435913c14926.png)

Is there an option I should be selecting or is this something that needs fixed?

Thanks for your help

Darren

**Comment by Djedouas** [comment] 2023-05-05 10:08
Ah yes! That's an error that we get the first time we log into the staging version.

Don't worry about this, if you log out, and log back in it should be gone.

**Comment by Traffic-Orders** [comment] 2023-05-05 11:04
It was working fine until I tried to create a permit bay between the disabled bay and DYLs below. This new bay did not appear and it looks like the same issue cropped up at that point.

![image](https://user-images.githubusercontent.com/109733089/236441776-e654aeb2-77ce-4a4b-b53e-49b473850a15.png)

Hope this has helped.

**Comment by Djedouas** [comment] 2023-05-05 12:21
Which type of permit bay exactly?

After adding this bay that disappears, can you add another type of bay?

**Comment by Traffic-Orders** [comment] 2023-05-09 14:18
It was a resident permit holders bay.

After the bay failed I could not create any more bays, tried P&D, shared use & Disabled. I could still create yellow lines

**Comment by Djedouas** [comment] 2023-05-11 08:13
I don't manage to reproduce the problem this time...

If I try to understand:
1. you were drawing bays
  1.1 clic on the create bay button ![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/75b0ad51-02c6-4b21-bbdc-a27ebd326616)
  1.2 draw the bay
  1.3 choose the attributes in the form
  1.4 validate the form, the create bay button disables itself
  1.5 back to the 1.1 step "clic on the create bay button"
2. then it stopped working, at which step?
3. you clicked on the create line button ![image](https://github.com/ProjectCentreLimited/TOMs/assets/34267385/dc6b6971-a342-4818-8c30-09b4cf5da6ed) and created yellow lines (following the same steps above, like for the bays)
4. did you try to go back to creating a bay?

Thanks,  
Jacky

**Comment by Traffic-Orders** [comment] 2023-06-05 08:40
Hi

As before it stops working at the last step. You go through everything necessary to add a bay or line and then it does not appear. It happens randomly and once it does I cannot add, remove or edit any restrictions.

It happened again late on Friday for proposal TRO/23/19. I was attempting to edit a yellow line to accommodate a new shared use and loading bay. I repositioned the SYL termination and then when it asks if I want to save. I selected yes and then the SYL snapped back to where it was. I then cannot edit, remove or add anything. Still in that position this morning. when I logged in again

**Comment by Traffic-Orders** [comment] 2023-06-05 09:00
Hi
As an update for this morning. Closing QGIS without logging out and re-opening has worked on the third attempt and I am now able to edit / remove / add restrictions again. Hopefully it will be a while before the glitch strikes again.

**Comment by Djedouas** [comment] 2023-06-05 13:22
Hi,

thanks for the last update. Were you on the staging or on the live version?

(you need to be on the staging version to test the update that I plan to put on the live version). 

Thanks

**Comment by Traffic-Orders** [comment] 2023-06-05 13:50
Hi,

This was on live as I have a proposal that needs drafting. The exact same issue crops up on staging though. Once something fails to be added removed or edited everything I try does the same thing. It then takes multiple attempts to close and re-open QGIS before it works again

**Comment by Djedouas** [comment] 2023-06-05 16:16
All right, I will look into it next week. Our company is having a seminar this week.

**Comment by Djedouas** [comment] 2023-06-26 14:49
Hi,

As you are mostly (if not always) working on the LIVE version of TOMS, and after I tested many times on the STAGING version, I pushed the modifications on the LIVE version.

Please let me know here if a problem occurs again with creation/removal/edition of a restriction, starting from now.

Thanks

**Comment by Traffic-Orders** [comment] 2023-06-28 09:40
Thank you. I will give it a try

**Closed as completed** 2023-06-28 09:40 UTC
