### ISSUE TITLE
Unable to remove restrictions

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#96] opened 2023-02-14 11:02 UTC
I am unable to remove restrictions from a proposal.

I have the proposal active in TOMS, hit select, choose the restriction (a DPPPP bay), hit remove restriction and it disappears. However when I try to remove the next DPPPP bay using the same method a message box appears that says "select restriction for edit" and the 1st DPPP bay reappears.

If I log out after removing the first bay it is back when I log back in too.

**Comment by Djedouas** [comment] 2023-02-16 08:56
Hi,

Could you give me the proposal title, please?

Also, which user account do you have? You can see it in the toolbar on the rightmost side (READ ONLY, WRITE, etc.).

Thanks.

**Comment by Djedouas** [comment] 2023-02-16 09:39
Can't reproduce the bug on the test system.

**Comment by Traffic-Orders** [comment] 2023-02-21 08:55
Hi, The proposal title is TRO/22/18 and I have a "write-live" account. The same issue is also occurring for another member of the team and they have the same account type.
I am attempting to remove the new disabled bays in Baileyfield Crescent and Adamslaw Place from the proposal at the request of our client, although the issue does not seem to be site or proposal specific. The only other info I can add is that the 2nd bay I select has 2 red crosses at it's extents in addition to being highlighted blue.

**Comment by Djedouas** [comment] 2023-02-21 10:01
Could you put a screen capture here please?

To show me one or more bays that you want to remove, so I can try to do it on the live system rather than on the test system.

Thanks

**Comment by Traffic-Orders** [comment] 2023-02-23 15:34
It is map tile 1408, proposal TRO/22/18 and I have circled the DPPPs in red that I am attempting to remove.

![Map Tile 1408](https://user-images.githubusercontent.com/109733089/220954680-947c2c98-6d6e-4560-9041-d092e46971e6.jpg)

**Comment by Djedouas** [comment] 2023-02-24 09:04
Thanks, I am able to reproduce the problem.

**Comment by Djedouas** [comment] 2023-02-24 10:11
This problem is related to a highly unstable part of TOMS, and not explicable yet... sorry.


I will keep this issue opened for future investigation.

Right now can you try this workaround please:
- log in
- wait for TOMS to launch
- close TOMS (discarding the current project)
- Re-open TOMS
- now the restriction remove tool should work

---


Close

![image](https://user-images.githubusercontent.com/34267385/221151908-c972a471-da9a-4994-932e-243d6c1b1e9e.png)


Re-open

![image](https://user-images.githubusercontent.com/34267385/221152095-54f0b98e-22bf-4029-bd57-a7b2d2d9b23a.png)

**Comment by Traffic-Orders** [comment] 2023-02-24 13:24
Obviously not ideal but the workaround does seem to work

**Comment by Traffic-Orders** [comment] 2023-03-03 10:17
Hi,

I've tried the workaround this morning a couple of times, but unfortunately, it doesn't appear to be working at the moment. Are there any updated available on this matter?

Many thanks

**Comment by Traffic-Orders** [comment] 2023-03-03 10:50
For info - managed to get the workaround to work after a laptop restart.

**Comment by Djedouas** [comment] 2023-04-24 12:41
Probably linked to #117

**Comment by Djedouas** [comment] 2023-05-09 08:50
Hi,

I have made a test to fix this problem. Can you give me your user name and email address so I can give you access to our testing version please?

Thanks

**Comment by Traffic-Orders** [comment] 2023-05-09 09:56
Hi,

I believe this is the same issue as #117. Same user/login

**Comment by Djedouas** [comment] 2023-05-09 10:05
All right, closing as duplicate

**Closed as completed by Djedouas** 2023-05-09 10:05 UTC
