### ISSUE TITLE
Splitting Tool 

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#32] opened 2022-10-18 10:16 UTC
Hi,

Hope you can help.
![Splitting tool 2](https://user-images.githubusercontent.com/109733089/196403358-30733148-7a6e-49ed-819d-6dfead290a7c.JPG)

I have just used the splitting tool to split a single yellow line and noticed that part of the split line jumped onto the pavement for some reason. In this case, this won't be a problem, as I will be deleting that part of the restriction.  However, this is something that should probably be looked into to ensure similar situation don't happen in the future.

Many thanks in advance.

**Comment by Djedouas** [comment] 2022-10-18 13:55
Hi,

I'm very interested into the exact location (and proposal) where this happened, to reproduce.

**Comment by Traffic-Orders** [comment] 2022-10-19 09:34
Hi,

This is location Bell's Mells, which is being amended under proposal TRO/22/16.

Many thanks

**Comment by Djedouas** [comment] 2022-10-19 15:26
Hi,

I was able to reproduce. 

It's not expected that the part of the yellow line jumps onto the pavement, but **this is a normal  behavior of TOMs**.

### Here is why and how to deal with it:

The direction to the road center is automatically computed when the geometry is drawn.  
This is a numerical value, which can be viewed and edited in the restriction details.
When the line is drawn, exactly onto the pavement limit, the resulting geometry appears 0.25m further towards the road center.

When the line is split, all small pieces keep the initial value of the direction to the road center.  
Everything goes well when the initial line has no big turn, because the direction to the road center does not change a lot.

Here we have a line which has an approximately 90° turn, with a direction to road center line of 152.

![image](https://user-images.githubusercontent.com/34267385/196732422-97b2db7b-7a89-4a70-85be-71914184ad4d.png)

When split at the top, everything works fine, we can see that 152 is a good value for this inclination.

![image](https://user-images.githubusercontent.com/34267385/196733531-c429a72a-4b26-4b5a-8d9c-427139b7312b.png)

When split on the left, the line jumps onto the pavement, because 152 is not good for the inclination of the bottom part.

![image](https://user-images.githubusercontent.com/34267385/196734180-e04491f1-b948-4f9d-8b8e-07eabae57e79.png)

So we have to change the direction to centerline, it's logical to try +/- 90° because of the 90° turn. It works with 152-90=62.

![image](https://user-images.githubusercontent.com/34267385/196734817-83289b31-058d-4958-be7e-721ce816a3a4.png)

The line jumps back on its good position.

---

This value is very important and it's good to play with it when the geometry does not fall on the right side.

**Comment by Djedouas** [comment] 2022-10-19 16:40
If it's clear enough for you, I let you close the issue.

**Comment by Traffic-Orders** [comment] 2022-10-20 11:57
Hi,

Afraid that this shouldn't be closed, as it does not resolve the issue for us. This was previously raised with PCL, as it's an ongoing matter. If we were to follow your instructions, that would cost us a lot of time whilst drafting - as this occurs on a regular basis (sometimes it rectifies itself if you start drafting from a different angle or draft the restriction in segments?). Is there a way to fix this permanently - stop it from happening?

Many thanks

**Comment by Djedouas** [comment] 2022-10-20 12:37
> Is there a way to fix this permanently - stop it from happening?

It's a complicated problem. Defining where is the road center direction depends on many situations.

Particularly when the restriction contains direction changes.

I see that you were familiar with this parameter, and for this splitting issue it solves the problem.

So I close this issue, which is specific to this split, and has been resolved, to open a more generic issue about this geometrical problem, which has to be investigated further: how to have a more reliable restriction placement?

**Closed as completed by Djedouas** 2022-10-20 12:37 UTC
Labels: geometry
