### ISSUE TITLE
TOMs rogue inclusion of map tile(s) TRO/21/17 = 1812 and TRO/21/15 = 1220 & 1279

### ISSUE THREAD

**Issue by SeanC75** [ProjectCentreLimited/TOMs#31] opened 2022-10-14 07:15 UTC
We cannot take TRO/21/18 forward to advert (various CPZ amendments including Nightingale Way) because TOMs has incorrect version numbers of tiles for 1279 & 1220. This appears to relate to the confirmed TRO/21/15 that TOMs only produced map tiles for 1221+1280 only, which were updated on 12/9/22 when that Order came info effect. Below is for info only relating to how I think this issue has come about

When TRO/21/15 was drafted by PCL, tiles 1221 & 1280 where shown on TOMs as affected by the proposed changes but when made 1220 & 1279 were also included (unbeknown to us)? I think this is something to do with a system update and that the line amended took in all 4 map tiles, see snippet below

 

Snippet from our files confirming only 2 tiles were shown when we were preparing the docs at making stage so seems there is a flaw in the system that allowed us to proceed to confirm an order which updated the version number of other tiles without any indicated in the proposed file on TOMs?

**Comment by SeanC75** [comment] 2022-10-17 10:05
Is it possible to take a look at this issue please? Let us know if more information is needed.

**Comment by Djedouas** [comment] 2022-10-18 07:48
I'll have a look today

**Comment by SeanC75** [comment] 2022-10-18 07:49
Thanks.

**Comment by Djedouas** [comment] 2022-10-18 14:05
If I understand correctly, tiles 1279 and 1220 currently have a version number of 6, which seems to have been wrongly increased during TRO/21/15, so they should have a version number of 5?

**Comment by Djedouas** [comment] 2022-10-18 16:48
Can you please describe what is technically blocking, at which step you see that the tile version number is incorrect, so I can reproduce (and learn) the workflow, and see what the problem is?

**Comment by SeanC75** [comment] 2022-11-01 10:36
@Djedouas is it possible to tag traffic orders in this item for them to reply as I don't seem to be able to?

**Comment by Djedouas** [comment] 2022-11-02 15:02
@Traffic-Orders

Can you please describe what is technically blocking, at which step you see that the tile version number is incorrect, so I can reproduce (and learn) the workflow, and see what the problem is?

**Comment by SeanC75** [comment] 2022-11-24 11:49
Need a new example if it happens again. Oslandia to check and fix the increase tile version number so rogue tiles are removed.

**Comment by Djedouas** [comment] 2022-11-28 15:25
@Traffic-Orders I decreased the revision number of tiles 1220 and 1279.

Can you please verify if everything is ok now?

Thanks

**Comment by Traffic-Orders** [comment] 2022-12-01 17:16
Hi

The rogue tile 1812 is still held in TOMs against TRO/21/17A? Can we be given a timescale for resolving this as we are being chased by the client to progress this Order?

Thanks
Sharon

**Comment by Djedouas** [comment] 2022-12-01 17:46
@Traffic-Orders 

3 days ago I decreased revision number for tiles 1220 & 1279, is it ok for TRO/21/15?

I have just decreased now the revision number for tile 1812, is it ok for TRO/21/17A?

Hope that's what you want (I try to understand "The rogue tile 1812 is still held in TOMs against TRO/21/17A").

If not, can you please describe **step by step** what you want to do, what is blocking and at **which step**, so I can reproduce (and learn) the workflow, and understand what the problem is?

Or, if more convenient for you, let's schedule a meeting next week.

**Comment by Traffic-Orders** [comment] 2022-12-01 19:26
Having seen the Oslandia response….

“I have just decreased now the revision number for tile 1812, is it ok for TRO/21/17A?

Hope that's what you want (I try to understand "The rogue tile 1812 is still held in TOMs against TRO/21/17A").

If not, can you please describe step by step what you want to do, what is blocking and at which step, so I can reproduce (and learn) the workflow, and understand what the problem is?

Or, if more convenient for you, let's schedule a meeting next week.”

My understanding is that this is yet another example of a long-standing issue that relates to a map tile not affected by any proposal being included in the proposal file for 21/17.

We shouldn’t have to explain this yet again, and yet here we are, explaining things for the umpteenth time. I’m fed up explaining to clients that no, we can’t advertise your order, and yes we’ll chase it again, and no we apparently don’t have any control, or can’t influence any inkling of urgency.

Honestly, it’s wearing so thin that I’m embarrassed to even mention TOMS. We are four years in to this arrangement and we still can’t rely on the system to draw lines where it’s supposed to, to include only map tiles with changes on them, or to even decide that it wants to allow us access on a regular basis or even to let us create proposals files!

I want someone to fix this, and I want it fixed immediately.

Andrew

Andrew MacKay
Senior Transport Team Leader – Traffic Regulations

•: ***@***.******@***.***>
•Network Management and Enforcement, Place, 4 East Market Street, Edinburgh, EH8 8BG

P  Please consider the environment before printing this email


From: Traffic Orders ***@***.***>
Sent: 01 December 2022 17:17
To: ProjectCentreLimited/TOMs ***@***.***>; ProjectCentreLimited/TOMs ***@***.***>
Cc: Traffic Orders ***@***.***>; Mention ***@***.***>
Subject: RE: [ProjectCentreLimited/TOMs] TOMs rogue inclusion of map tile(s) TRO/21/17 = 1812 and TRO/21/15 = 1220 & 1279 (Issue #31)

Hi

The rogue tile 1812 is still held in TOMs against TRO/21/17A? Can we be given a timescale for resolving this as we are being chased by the client to progress this Order?

Thanks
Sharon

**Comment by Traffic-Orders** [comment] 2022-12-02 06:16
Morning

For TRO/21/17A the map tile 1812 should not be contained within the proposal so it should be removed. There should not be a need to revise the version number of this tile as it is currently held in a proposal and will not be included in the upcoming advertised Order. Please confirm when the tile 1812 will be removed from the proposal TRO/21/17A on TOMs?

Isabelle will check the info re tile versions for 1220 & 1279 as per TRO/21/15 which affected a proposal she is taking forward for TRO/21/18. She will let you know if any further action is required for map tiles 1220 & 1279.

Thanks
Sharon

**Comment by SeanC75** [comment] 2022-12-05 11:22
@Djedouas Is there anything you need to progress this issue?

**Comment by Djedouas** [comment] 2022-12-06 10:09
## TRO-21-17A

I finally found that this bay has been edited at some point, in this proposal, inside tile 1812.

![image](https://user-images.githubusercontent.com/34267385/205882199-8eae26ad-b87e-4826-857c-08734a8eaacb.png)

I removed all history of this bay being edited.

Now, tile 1812 is no longer included in the proposal.

**Comment by Djedouas** [comment] 2022-12-06 10:15
I suppose that TRO-21-15 problem has been fixed because this proposal has been accepted.

**Comment by Djedouas** [comment] 2022-12-06 10:17
@Traffic-Orders you can check on TOMs, and confirm that everything is fixed by closing this issue.

Thanks.

**Comment by Traffic-Orders** [comment] 2022-12-12 17:03
Hi

Thank you for the info.

Not sure why anyone would have edited that bay as the proposal TRO/21/17A had no request to amend anything on West Newington Road. I also note that map tile 1812 is now no longer part of this proposal which allows us to take this forward to advert and resolves issue 31.

Thanks
Sharon

**Comment by Traffic-Orders** [comment] 2022-12-12 17:07
Sorry I incorrectly referenced West Newington Road, should be West Newington Place

From: Traffic Orders
Sent: 12 December 2022 17:03
To: ProjectCentreLimited/TOMs ***@***.***>; ProjectCentreLimited/TOMs ***@***.***>
Cc: Traffic Orders ***@***.***>; Mention ***@***.***>; Sean Casey ***@***.***>
Subject: RE: [ProjectCentreLimited/TOMs] TOMs rogue inclusion of map tile(s) TRO/21/17 = 1812 and TRO/21/15 = 1220 & 1279 (Issue #31)

Hi

Thank you for the info.

Not sure why anyone would have edited that bay as the proposal TRO/21/17A had no request to amend anything on West Newington Road. I also note that map tile 1812 is now no longer part of this proposal which allows us to take this forward to advert and resolves issue 31.

Thanks
Sharon

**Comment by Djedouas** [comment] 2022-12-12 17:26
Closing issue as @Traffic-Orders confirmed that the issue can be resolved

> I also note that map tile 1812 is now no longer part of this proposal which allows us to take this forward to advert and resolves issue 31.

**Closed as completed by Djedouas** 2022-12-12 17:26 UTC
Labels: waiting user feedback
