### ISSUE TITLE
Log in details for TOMs not working

### ISSUE THREAD

**Issue by andreslices** [ProjectCentreLimited/TOMs#46] opened 2022-11-01 14:29 UTC
Hello, the log in details I have been given do not work: 

Username: andres.lices

[https://toms.mhtc.co.uk/guacamole/#/client/MTIzAGMAcG9zdGdyZXNxbA==](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftoms.mhtc.co.uk%2Fguacamole%2F%23%2Fclient%2FMTIzAGMAcG9zdGdyZXNxbA%3D%3D&data=05%7C01%7CEduardo.Moral%40projectcentre.co.uk%7Cd3c1b5d2ace84856843f08da95753b4c%7C3734172ae82a4ac7a3d302949970d5e6%7C0%7C0%7C637986627988621966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Fdj6RfPriDBwThNjzds2PFeFZimVsfrqhpaC9QfJj1k%3D&reserved=0)

I get "Invalid Login".

Thanks,

**Comment by benoitdm-oslandia** [comment] 2022-11-02 10:03
hi @andreslices, you are using the old TOMs link. Please use the one provided in the AWS email.

**Comment by andreslices** [comment] 2022-11-02 10:12
Good morning,

I am not sure what the AWS email is? Eduardo, is this something you received?

Kind regards,

Andres Lices
Senior Engineer, Waste – Communal Bin Review Project Team – Waste and Cleansing Services – Place Management – The City of Edinburgh Council – Business Centre G.4. – Waverley Court – Edinburgh – EH8 8BG M: 077 0889 9569 Email: ***@***.******@***.***>
***@***.***  Chat with me in ***@***.***>

***@***.***

**Comment by benoitdm-oslandia** [comment] 2022-11-02 10:28
You have received an email with a link to login into the AppStream and with your password. This password can be changed when you first connect. The login page link and the changed password cannot be retrieved if lost, please, SAVE THEM with caution.

Then you have received a second email to inform you have been assign to the TOMs CEC application.

**Comment by andreslices** [comment] 2022-11-02 10:36
Hi,

I have tried any single password that I use without any luck.

I do not recall having changed the password.

Furthermore, for good practice I use a password manager and add/update passwords as required for each site I use. The password I saved for this site does not work.

If it is impossible to recover the password. Could my username be deleted and created again?

Kind regards,

Andres Lices
Transport Officer (Project Management), Active Travel – Road Safety & Active Travel – Place-making and Mobility – Place – The City of Edinburgh Council – Business Centre G.4. – Waverley Court – Edinburgh – EH8 8BG T: 07563376596 Email: ***@***.******@***.***>
***@***.***  Chat with me in ***@***.***>

***@***.***

**Comment by andreslices** [comment] 2022-11-02 11:01
Hi Andres,

Yes, when a new account is created you should receive an email from AWS with the link and temporary password (see below mine for reference).
If you have not received this email please contact your IT department to make sure that if an email from @accounts-eu-west........... was sent to you and quarantined it is removed from quarantine so you can access the login page.

***@***.***

Hope this helps,
Eduardo
Eduardo Martin-Moral MEng, CEng, MICE, NECReg
Principal Engineer

Project Centre, part of Marston Holdings
https://www.marstonholdings.co.uk/projectcentre<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.marstonholdings.co.uk%2Fprojectcentre&data=04%7C01%7CEduardo.Moral%40projectcentre.co.uk%7Cb49c25a9434a4ac07e8a08d9d04303dc%7C3734172ae82a4ac7a3d302949970d5e6%7C0%7C0%7C637769808502854253%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yL6vz9%2BtL0WmSNWmQa5v6iUkff6SKUFH90Swq3qaHoA%3D&reserved=0>

Company information: Project Centre Limited, Registered Office: Rutland House, 8th Floor, 148 Edmund Street, Birmingham, B3 2JR. Registered in England and Wales number 4305487. Confidentiality notice This message is intended solely for the addressee and may contain confidential information. If you have received this message in error, please send it back to us, and immediately and permanently delete it. Do not use, copy or disclose the information contained in this message or in any attachment. Privacy policy For information about how we process data please see our privacy policy at https://marstonholdings.co.uk/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmarstonholdings.co.uk%2F&data=05%7C01%7CEduardo.Moral%40projectcentre.co.uk%7Ce6ba52d06770440abffa08da4d481d62%7C3734172ae82a4ac7a3d302949970d5e6%7C0%7C0%7C637907269375101670%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Qt0KcTG%2BzLYvQTwlKi%2Bx%2FCnMJvGrgqWLGy2xiOdP3Sw%3D&reserved=0>
Due to my flexible working pattern, I may send emails outside of normal working hours. Please don't reply outside your working day. Be safe and healthy.



From: Andres Lices ***@***.***>
Sent: 02 November 2022 10:13
To: ProjectCentreLimited/TOMs ***@***.***>; ProjectCentreLimited/TOMs ***@***.***>
Cc: Mention ***@***.***>; Eduardo Moral ***@***.***>
Subject: RE: [ProjectCentreLimited/TOMs] Log in details for TOMs not working (Issue #46)

Caution: This e-mail originates from outside MHL, exercise caution with any instructions in the content, attachments, or links.

Good morning,

I am not sure what the AWS email is? Eduardo, is this something you received?

Kind regards,

Andres Lices
Senior Engineer, Waste - Communal Bin Review Project Team - Waste and Cleansing Services - Place Management - The City of Edinburgh Council - Business Centre G.4. - Waverley Court - Edinburgh - EH8 8BG M: 077 0889 9569 Email: ***@***.******@***.***>
***@***.***  Chat with me in Teams<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fchat%2F0%2F0%3Fusers%3Dandres.lices%40edinburgh.gov.uk&data=05%7C01%7CEduardo.Moral%40projectcentre.co.uk%7C4d1b0f33c1a746692fc308dabcbac6e0%7C3734172ae82a4ac7a3d302949970d5e6%7C0%7C0%7C638029807633620418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aV1BcbmbAZwHRpQN6Ujw%2FNXK%2B9qS8lQn2%2BGLeTCzuW8%3D&reserved=0>

***@***.***

**Comment by andreslices** [comment] 2022-11-04 14:20
Any updates on this? I have no trace of the AWS email.

**Comment by benoitdm-oslandia** [comment] 2022-11-07 07:25
@andreslices I can resent you the email but if the issue is linked to some IT filtering, it will be useless. Do you have any confirmation from your IT, the domain `@accounts.eu-west-2.amazonappstream.com` has been allowed?

**Comment by andreslices** [comment] 2022-11-29 12:09
Hello,

I have finally managed to speak with my IT administrator. They have confirmed that if it gets caught on the IT filter I should received a notification to release it manually myself.

Can you please resend and send evidence of this action to investigate or hopefully prove that it works.

Thanks very mcuh,

Andres Lices
Senior Engineer, Waste – Communal Bin Review Project Team – Waste and Cleansing Services – Place Management – The City of Edinburgh Council – Business Centre G.4. – Waverley Court – Edinburgh – EH8 8BG M: 077 0889 9569 Email: ***@***.******@***.***>
***@***.***  Chat with me in ***@***.***>

***@***.***

**Comment by benoitdm-oslandia** [comment] 2022-11-30 07:20
Ok I have just recreate the account and send the email.

Regards.

**Comment by andreslices** [comment] 2022-11-30 10:03
This is perfect, emails have arrived.

Thanks for your help.

Andres Lices
Senior Engineer, Waste – Communal Bin Review Project Team – Waste and Cleansing Services – Place Management – The City of Edinburgh Council – Business Centre G.4. – Waverley Court – Edinburgh – EH8 8BG M: 077 0889 9569 Email: ***@***.******@***.***>
***@***.***  Chat with me in ***@***.***>

***@***.***

**Comment by benoitdm-oslandia** [comment] 2022-11-30 13:01
If you have been able to connect to TOMs, then can you close this issue please?

**Comment by andreslices** [comment] 2022-11-30 13:03
I have been able to log to TOMS. Is it me who needs to close it?

Thanks,

Andres Lices
Senior Engineer, Waste – Communal Bin Review Project Team – Waste and Cleansing Services – Place Management – The City of Edinburgh Council – Business Centre G.4. – Waverley Court – Edinburgh – EH8 8BG M: 077 0889 9569 Email: ***@***.******@***.***>
***@***.***  Chat with me in ***@***.***>

***@***.***

**Comment by benoitdm-oslandia** [comment] 2022-11-30 13:14
You could do it at any time. But I will for now!

Regards.

**Closed as completed by benoitdm-oslandia** 2022-11-30 13:14 UTC
Labels: Service_Level_0
