### ISSUE TITLE
Proposal missing

### ISSUE THREAD

**Issue by holly-robertson** [ProjectCentreLimited/TOMs#105] opened 2023-03-16 12:35 UTC
Hi there, 

I made a proposal for TRO/22/08 but it seems to have disappeared, I done a lot of work on this proposal so if you could somehow restore it. It hasn't appeared on the proposal list since last Thursday. My other team members can't see the proposal either, i also am having trouble creating new proposals as they seem to delete themselves after being made?

**Comment by Djedouas** [comment] 2023-03-17 16:48
Hi,

That's a huge problem...

I looked for TRO/22/08 in our backup from last Monday (13th March), and the Monday before (6th March), to no avail.  
Should I continue looking for this proposal even earlier? Or maybe you can remember a date I can look?

Have you created another proposal recently, which disappeared? And have you created one that is still available?

I created a proposal in our TOMS staging/test system to see if it disappears...

**Comment by Djedouas** [comment] 2023-04-06 12:14
closing as duplicate of #112

**Closed as completed by Djedouas** 2023-04-06 12:14 UTC
