### ISSUE TITLE
TOMs getting stuck on an action while drafting

### ISSUE THREAD

**Issue by Traffic-Orders** [ProjectCentreLimited/TOMs#33] opened 2022-10-18 10:22 UTC
Hi,

To make you aware, there appears to be an issue with TOMs randomly getting stuck on an action while drafting, forcing you to log out and sign in again (this will be restart number 5/6 today).

Found this difficult to screenshot to provide an example, but made an attempt:
![TOMs getting stuck](https://user-images.githubusercontent.com/109733089/196404505-0be7da0c-1083-44bf-b799-16a7eb38935d.JPG)

**Comment by Djedouas** [comment] 2022-10-18 13:53
Hi,

Thanks for the screenshot attempt, it could be of huge help.

This one is not really clear as to what the problem is, I can see that TOMs toolbar is completely disabled (tools and icons are gray) and should never be during drawing, how did it happen?

**Comment by Traffic-Orders** [comment] 2022-10-19 09:28
Hi,

The toolbar is greyed out as I was trying to get in out of the proposal to get things working again - afraid nothing changed, and the action remained stuck until I logged out of TOMs.

Many thanks

**Comment by Djedouas** [comment] 2022-10-19 15:29
Does it happen when creating the restriction, or drawing construction lines, or editing...? which specific tool? or any tool?

**Comment by Traffic-Orders** [comment] 2022-10-19 15:37
Hi,

So far it happened when I drew yellow line restrictions, a bay and constructions lines, not sure if it would happen with other tools.

**Comment by Djedouas** [comment] 2022-10-19 16:05
What do you mean by "getting stuck on an action"? Is everything frozen? Every other tool, the map...

Maybe in the status bar there is something going on, loading...?

![image](https://user-images.githubusercontent.com/34267385/196745104-d517a726-d35e-43ec-b25b-06caa644db56.png)

**Comment by Traffic-Orders** [comment] 2022-10-19 16:15
Hi,

I suppose frozen would be a good synonym. I'm not sure how else to describe it, nothing appears to be loading and the only thing that appears to unfreeze the previously selected action, is signing out and back in.

**Comment by Djedouas** [comment] 2022-10-19 16:30
Difficult issue...

For sure, signing out and back in resolves the problem, because it completely resets all TOMs interface and all tools.

**Comment by Djedouas** [comment] 2022-10-25 12:37
Hi,

Is it still happening?

**Comment by Traffic-Orders** [comment] 2022-10-31 12:24
Hi,

Would it be possible for this to be checked in a test system on your end?

Many thanks

**Comment by Djedouas** [comment] 2022-10-31 14:47
We have yet to create the test system.

However, I've been drafting some restrictions in a test proposal from time to time, and never experienced any freeze 😕

**Comment by Djedouas** [comment] 2023-02-16 09:11
No update for 3 months, considering fixed, closing.

**Closed as completed by Djedouas** 2023-02-16 09:11 UTC
Labels: bug, not reproduced
